# Generated by Django 3.0.6 on 2020-05-31 09:21

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('IPv4', models.GenericIPAddressField(protocol='IPv4')),
                ('Port', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
                ('StreamName', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'Camera',
            },
        ),
    ]
