# Generated by Django 3.0.6 on 2020-05-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartoonServiceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'managed': True},
        ),
    ]
